name: Auto Deploy Backend

on:
  push:
    branches:
      - main  # deploys whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VPS and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}          # VPS IP
          username: root
          key: ${{ secrets.AUTO_DEPLOY_KEY }}    # Private key you added as secret
          port: 22
          script: |
            source ~/.profile
            cd /var/www/auto.nostapay.com
            git reset --hard
            git pull origin main
            /root/.nvm/versions/node/v24.11.1/bin/npm install
            /root/.nvm/versions/node/v24.11.1/bin/pm2 restart auto-backend
